@startuml Diagrama de Classes

' O controller recebe o input do usuário, pega os dados com o model e passa isso pra view

' View 
package View {
    class Menu {
        - InputUtil input;

        + Menu(InputUtil input) 
        + void menuPrincipal()
        + void menuPrincipalCliente()
        + void menuPrincipalAdministrador()

        + void mostrarExtrato(ExtratoDTO extrato)
        + void mostrarInfoUsuario(UserDTO usuario)
    }

    class TextColor {
        + static final String RED
        + static final String GREEN
        + static final String RESET
    }
}

' Controller
package Controller {
    class AdminController {
        - AdminService admService
        
        + AdminController(AdminService admService)
        + void bloquearCliente(String emailCliente)
        + void desbloquearCliente(String emailCliente)
        + UserDTO getInfoUsuario(String emailCliente)
        + void cadastrarCliente(String nome, String senha, String email, String cpf, double rendaMensal)
    }

    class ContaController {
        - ContaService contaService
        - MonetaryService monetaryService
        - ExtratoService extratoService
        
        + ContaController(ContaService contaService, MonetaryService monetaryService, ExtratoService extratoService)
        + void sacar(double valor) 
        + void depositar(double valor)
        + void realizarPagamento(double valor)
        + double verSaldo()
        + ExtratoDTO pegarExtrato()
    }
}

' Model
package Model {
    ' O model contém classes de dados (que guardam dados e fazem operações simples consigo mesma)
    ' ou classes de de gerenciamento / serviço (que vão fazer operações mais complexas envolvendo entidades distintas) 
    
    ' Usuário
    enum NivelUsuarioEnum {
        "Admin",
        "Cliente"
    }

    abstract class UsuarioAbstrato {
        - String nome
        - String senha
        - String email
        - String cpf
        - NivelUsuarioEnum tipoUsuario

        + Usuario(String nome, String senha, String email, String cpf, NivelUsuario cargo)
        + void atualizarDados()
    }

    ' Posso colocar campos únicos para essas classes aqui
    class Admin {
        - String matricula

        + Admin(String nome, String senha, String email, String cpf, String matricula)
        + String converterParaStringArmazenavel()
    }

    class Cliente {
        - double rendaMensal

        + Cliente(String nome, String senha, String email, String cpf, double rendaMensal)
        + String converterParaStringArmazenavel()
    }

    ' Conta
    abstract class ContaAbstrata {
        - double saldo 
        - String emailTitular 
        - String tipoConta
        - IContaState estadoConta

        + Conta(double saldo, Usuario titularConta, ExtratoBancario extrato, IContaState estadoInicial)
        + void mudarEstado(IContaState novoEstado)
        + void creditar(double quantidade)
        + void debitar(double quantidade)
        + void deletarConta()
    }

    class ContaCorrente {
        ' O cheque especial vai ser 10% da renda mensal
        - double chequeEspecial

        + ContaCorrente(double saldo, Usuario titularConta, ExtratoBancario extrato, IContaState estadoInicial, double chequeEspecial)
        ' O método de debitar vai ser sobreescrito para
        ' permitir o uso do cheque especial
        + void debitar(double quantidade)
    }

    ' Extrato Bancário
    class OperacaoExtratavel {
        - String nomeOperacao;
        - double valorDaOperacao;

        + OperacaoExtratavel(String nomeOperacao, double valorDaOperacao)
    }

    class ExtratoBancario{
        - List<OperacaoExtratavel> operacoesRealizadas
        - String emailTitular

        + ExtratoBancario() 
        + void adicionarOperacao(OperacaoExtratavel operacao)
    }


    ' Relacionamentos do model

    ' Relacionamento do usuário
    UsuarioAbstrato <|-down- Admin
    UsuarioAbstrato <|-down- Cliente
    UsuarioAbstrato -left-> NivelUsuarioEnum

    ' Relacionamento das contas
    ContaAbstrata <|-- ContaCorrente
    ContaAbstrata *-left- Usuario : 1 tem 1
    ContaAbstrata *-right- ExtratoBancario : 1 tem 1 

    ' Relacionamento do extrato
    ExtratoBancario *-down- OperacaoExtratavel : 1 tem N >



    ' Packages internos
    package Services{
        ' Serviços serão classes que auxiliarão classes de dados a se relacionar com outras classes
        class AutenticacaoService {
            + boolean verificarLogin(String email, String senha)
        }
        
        class AdminService{
            - UserRepository userRepo
            - UserMapper userMapper

            + AdminService(UserRepository userRepo, UserMapper userMapper)
            + void cadastrarCliente(String nome, String senha, String email, String cpf, double rendaMensal, ContaFactory tipoConta)
            + void bloquearContaCliente(String email)
            + void desbloquearContaCliente(String email)

            + UserDTO getInfoUsuario(String email)
        }

        class ContaService {
            ' Essa conta pode utilizar do padrão observer para notificar o repositório de contas de operações realizadas
            ' Isso impediria da própria classe Conta lidar com esse processo.

            ' O sistema vai utilizar do sessionManager pra pegar a conta do cliente logado
            - SessionManager sessionManager
            - ContaRepository contaRepo

            + ContaService(SessionManager sM, ContaRepository contaRepo)
            + void bloquearConta(Usuario cliente)
            + void desbloquearConta(Usuario cliente)

            ' Metódo futuro a ser implementado
            + ContaDTO mostrarInfoConta()
        }

        class MonetaryService {
            - ContaRepository contaRepo;
            - SessionManager sessionManager;
            - PagamentoService pagamentoService;

            + MonetaryService(ContaRepository contaRepository, SessionManager sessionManager, PagamentoService pagamentoService)

            + void sacar(double valor)
            + void depositar(double valor)
            + void realizarPagamento(double valor)
        }

        class ExtratoService {
            - ExtratoMapper mapper 
            - ExtratoRepository extratoRepo 
            - SessionManager sessionManager

            + ExtratoService(ExtratoMapper mapper, ExtratoRepository extratoRepo, SessionManager sessionManager)
            + ExtratoBancarioDTO pegarExtrato(ExtratoBancario extrato)
        }

        class PagamentoService{
            - IPaymentStrategy pagamentoStrategy

            + PagamentoService()
            + void setStrategy(IPaymentStrategy strategy)
            + double realizarPagamento(double quantia)
        }

        ' Relacionamentos dos serviços
        AdminService <-up- AdminController
        ContaService <-up- ContaController
        MonetaryService <-up- ContaController
        ExtratoService <-up- ContaController

        MonetaryService *-- PagamentoService
        
    }
}

' Util
package Util{
    class InputUtil {
        - Scanner sc

        + String getAlphaInput()
        + String getStringInput()
        + int getIntInput()
        + double getDoubleInput()

        ' Métodos futuros
        + String getCPFInput()
        + String getEmailInput()
    }

    class FinancaUtil {
        + static double calcularChequeEspecial(double rendaMensal)
    }
}

' DTOs
package DTOs {
        class OperacaoExtratavelDTO {
            - String nomeOperacao
            - double valorOperacao

            + OperacaoExtratavelDTO(String nomeOperacao, double valorOperacao)
        }

        class ExtratoBancarioDTO{
            - List<OperacaoExtratavelDTO> operacoesRealizadas

            + ExtratoBancarioDTO(List<OperacaoExtratavel> operacoesRealizadas)
        }

        class UserDTO {
            - String nome
            - String email
            - String cpf
            - NivelUsuario cargo

            + UserDTO(Usuario user)
            + String toString()
        }

        class ClienteDTO{
            - double rendaMensal
            
            + String toString()
        }

        ' Essas 2 classes ainda não foram implementadas
        class ContaDTO{

        }

        class ContaCorrenteDTO

        ExtratoBancarioDTO *-left- OperacaoExtratavelDTO
        ClienteDTO -up-|> UserDTO
}

' Mappers 
package Mappers{
    class ExtratoMapper {
        + ExtratoBancarioDTO extratoToDTO(ExtratoBancario extrato)
    }

    class UserMapper{
        + ClienteDTO clienteToDTO(Cliente cliente)
    }

    ' Não foi implementada ainda.
    class ContaMapper{

    }
}

' State
package State {
    interface IContaState{
        + boolean podeDeletarConta()
        + boolean podeDebitar()
        + boolean podeCreditar()
        + boolean podePegarExtrato()
        + String getStateName()
    }

    class ContaPositiva {

    }

    class ContaNegativada {

    }

    class ContaBloqueada {

    }

    class ContaEncerrada {

    }

    ' Relacionamento dos estados contas 
    ContaAbstrata *--right- IContaState
    IContaState <|.. ContaPositiva
    IContaState <|.. ContaNegativada
    IContaState <|.. ContaBloqueada
    IContaState <|..right. ContaEncerrada
}

' Strategy
package Strategy{
    interface IPaymentStrategy {
        + double pagar(Conta conta, double valor)
    }

    class EspecieStrategy {
        + double pagar(Conta conta, double valor)
    }

    class InternetBankingStrategy {
        + double pagar(Conta conta, double valor)
    }

    ' Relacionamentos
    IPaymentStrategy <|.up. EspecieStrategy
    IPaymentStrategy <|.up. InternetBankingStrategy 

    IPaymentStrategy .up.* PagamentoService
}

' Factory
package Factory{
    package ContaFactory{
        interface ContaFactory {
            + ContaAbstrata criarConta(Usuario usuario)
        }

        class ContaCorrenteFactory {
            + ContaAbstrata criarConta(Usuario usuario)
        }


        ContaFactory <|.. ContaCorrenteFactory
    }
    
    ' Caso for aplicar o factory method para trazer os usuários do arquivo
    package UserFactory{
        interface UserFactory {
            + UsuarioAbstrato criarUsuario()
        }

        class ClienteFactory {
            + UsuarioAbstrato criarUsuario()
        }

        UserFactory <|.. ClienteFactory
    }
}

' Singletons
package SingletonRepositories {
    ' Provavelmente vou salvar os dados em arquivos
    ' Classes que vão guardar conjuntos de dados

    ' Interface para salvamento
    interface IStorable {
        ' Com a implementação do Gson essa classe perdeu a utilidade, servindo apenas para garantir que o repositório seja de algo guardável
    }

    IStorable <|.down. UsuarioAbstrato
    IStorable <|.down. ContaAbstrata
    IStorable <|.down. ExtratoBancario
    IStorable <|.down. OperacaoExtratavel
    
    abstract class BaseRepository<T extends IStorable>{
        + void salvar(T entidade)
        + void deletar(T entidade) 
        + abstract T carregarEntidade(String textoArmazenado)
        + abstract String getFileName()
    }
    
    class UserRepository {
        - static UserRepository instance

        + UserRepository()
        + static UserRepository getInstance()
        + UsuarioAbstrato pegarPorEmail(String email)
        + UsuarioAbstrato carregarEntidade(String textoArmazenado)
    }

    class ContaRepository {
        - static ContaRepository instance

        + ContaRepository()
        + static ContaRepository getInstance()
        + ContaAbstrata pegarPorTitular(String emailTitular)
        + ContaAbstrata carregarEntidade(String textoArmazenado)
    }

    class ExtratoRepository {
        - static ExtratoRepository instance

        + ExtratoRepository()
        + static ExtratoRepository getInstance()
        + ExtratoBancario pegarPorTitular(String email)
        + ExtratoBancario carregarEntidade(String textoArmazenado)
    }

    ' Relacionamentos
    BaseRepository <|.up. UserRepository 
    BaseRepository <|.up. ContaRepository 
    BaseRepository <|.up. ExtratoRepository
    BaseRepository --> IStorable
}

package SingletonSession{
    class SessionManager {
        - static SessionManager instance
        - UsuarioAbstrato usuarioLogado
        - ContaAbstrata contaAtiva

        - SessionManager()
        + static SessionManager getInstance()
    }
}

@enduml