@startuml Diagrama de Classes

' O controller recebe o input do usuário, pega os dados com o model e passa isso pra view

' View 
package View {
    class Menu {
        - InputUtil input;

        + Menu(InputUtil input)
        + int menuPrincipal()
        + int menuPrincipalCliente()
        + int menuPrincipalAdministrador()

        + void mostrarExtrato(ExtratoDTO extrato)
        + void mostrarInfoUsuario(UserDTO usuario)
    }

    class TextColor {
        + static final String RED
        + static final String GREEN
        + static final String RESET
    }
}

' Controller
package Controller {
    class AdminController {
        - AdminService admService
        - InputUtil inputUtil

        + AdminController(AdminService admService, InputUtil inputUtil)
        + void bloquearCliente(int clienteId)
        + void desbloquearCliente(int clienteId)
        + UserDTO getInfoUsuario(int clienteId)
        + void cadastrarCliente()
    }

    class ContaController {
        - ContaService contaService

        + ContaController(ContaService contaService)
        + void sacar(double valor)
        + void depositar(double valor)
        + void realizarPagamento(double valor)
        + ExtratoBancarioDTO pegarExtrato()
    }
}

' Model
package Model {
    ' O model contém classes de dados (que guardam dados e fazem operações simples consigo mesma)
    ' ou classes de de gerenciamento / serviço (que vão fazer operações mais complexas envolvendo entidades distintas)

    ' Usuário
    enum NivelUsuario {
        "Admin",
        "Cliente"
    }

    abstract class Usuario {
        - int id
        - String nome
        - String senha
        - String email
        - String cpf
        - NivelUsuario cargo

        + Usuario(String nome, String senha, String email, String cpf, NivelUsuario cargo)
        'Verifica se a estrutura da senha é válida
        + boolean validarSenha(String senha)
        + void atualizarDados()
    }

    ' Posso colocar campos únicos para essas classes aqui
    class Admin {
        - String matricula

        + Admin(String nome, String senha, String email, String cpf, String matricula)
    }

    class Cliente {
        - double rendaMensal

        + Cliente(String nome, String senha, String email, String cpf, double rendaMensal)
    }

    ' Conta
    abstract class Conta {
        - int id
        - double saldo
        - Usuario titularConta
        - ExtratoBancario extrato
        - IContaState estadoConta

        + Conta(double saldo, Usuario titularConta, ExtratoBancario extrato, IContaState estadoInicial)
        + void mudarEstado(IContaState novoEstado)
        + void creditar(double quantidade)
        + void debitar(double quantidade)
        + void deletarConta()
    }

    class ContaCorrente {
        ' O cheque especial vai ser 10% da renda mensal
        - double chequeEspecial

        + ContaCorrente(double saldo, Usuario titularConta, ExtratoBancario extrato, IContaState estadoInicial, double chequeEspecial)
        ' O método de debitar vai ser sobreescrito para
        ' permitir o uso do cheque especial
        + void debitar(double quantidade)
        + void usarChequeEspecial()
    }

    ' Extrato Bancário
    class OperacaoExtratavel {
        - String nomeOperacao;
        - double valorDaOperacao;

        + OperacaoExtratavel(String nomeOperacao, double valorDaOperacao)
    }

    class ExtratoBancario{
        - List<OperacaoExtratavel> operacoesRealizadas

        + ExtratoBancario()
        + void adicionarOperacao(OperacaoExtratavel operacao)
    }


    ' Relacionamentos do model

    ' Relacionamento do usuário
    Usuario <|-down- Admin
    Usuario <|-down- Cliente
    Usuario -left-> NivelUsuario

    ' Relacionamento das contas
    Conta <|-- ContaCorrente
    Conta *-left- Usuario : 1 tem 1
    Conta *--right-- ExtratoBancario : 1 tem 1

    ' Relacionamento do extrato
    ExtratoBancario *-- OperacaoExtratavel : 1 tem N >



    ' Packages internos
    package Services{
        ' Serviços serão classes que auxiliarão classes de dados a se relacionar com outras classes
        class AutenticacaoService {
            + boolean verificarLogin(String email, String senha)
        }

        class AdminService{
            - UserRepository userRepo

            + AdminService(UserRepository userRepo)
            + void cadastrarCliente(String nome, String senha, String email, String cpf, double rendaMensal, ContaFactory tipoConta)
            + void bloquearCliente(int id)
            + void desbloquearCliente(int id)
            + UserDTO getInfoUsuario(int id)
        }

        class ContaService {
            ' O sistema vai utilizar do sessionManager pra pegar a conta do cliente logado
            - SessionManager sessionManager
            - ContaRepository contaRepo
            - PagamentoService pagamentoService

            + ContaService(SessionManager sM, ContaRepository contaRepo, PagamentoService pS)
            + void sacar(double valor)
            + void depositar(double valor)
            + void realizarPagamento(double valor)
            + void bloquearConta(Usuario cliente)
            + void desbloquearConta(Usuario cliente)
            + ExtratoBancario pegarExtrato()
        }

        class PagamentoService{
            - IPaymentStrategy pagamentoStrategy

            + PagamentoService()
            + void setStrategy(IPaymentStrategy strategy)
            + void realizarPagamento(double quantia)
        }

        ' Relacionamentos dos serviços
        AdminService <-up- AdminController
        ContaService <-up- ContaController

    }
}

' Util
package Util{
    class InputUtil {
        - Scanner sc

        + String getAlphaInput()
        + int getIntInput()
        + String getStringInput()
    }

    class FinancaUtil {
        + static double calcularChequeEspecial(double rendaMensal)
    }
}

' DTOs
package DTOs {
        class OperacaoExtratavelDTO {
            - String nomeOperacao
            - double valorOperacao

            + OperacaoExtratavelDTO(String nomeOperacao, double valorOperacao)
        }

        class ExtratoBancarioDTO{
            - List<OperacaoExtratavelDTO> operacoesRealizadas

            + ExtratoBancarioDTO()
            + void adicionarOperacao()
        }

        class UserDTO {
            - int id
            - String nome
            - String senha
            - String email
            - String cpf
            - NivelUsuario cargo

            + UserDTO(Usuario user)
            + String tostring()
        }

        ExtratoBancarioDTO -- ExtratoBancario
        ExtratoBancarioDTO *-left- OperacaoExtratavelDTO
}

' State
package State {
    interface IContaState{
        + boolean podeDeletarConta()
        + boolean podeDebitar()
        + boolean podeCreditar()
        + boolean podePegarExtrato()
    }

    class ContaPositiva {
        - Conta conta
        + ContaPositiva(Conta conta)
    }

    class ContaNegativada {
        - Conta conta
        + ContaNegativada(Conta conta)
    }

    class ContaBloqueada {
        - Conta conta
        + ContaBloqueada(Conta conta)
    }

    class ContaEncerrada {
        - Conta conta
        + ContaEncerrada(Conta conta)
    }

    ' Relacionamento dos estados contas
    Conta *--right- IContaState
    IContaState <|.. ContaPositiva
    IContaState <|.. ContaNegativada
    IContaState <|.. ContaBloqueada
    IContaState <|..right. ContaEncerrada
}

' Strategy
package Strategy{
    interface IPaymentStrategy {
        + void pagar(Conta conta, double valor)
    }

    class EspecieStrategy {
        + void pagar(Conta conta, double valor)
    }

    class InternetBankingStrategy {
        + void pagar(Conta conta, double valor)
    }

    ' Relacionamentos
    IPaymentStrategy <|.up. EspecieStrategy
    IPaymentStrategy <|.up. InternetBankingStrategy

    IPaymentStrategy .down.* PagamentoService
}

' Factory
package Factory {
    interface ContaFactory {
        + Conta criarConta(Usuario usuario)
    }

    class ContaCorrenteFactory {
        + Conta criarConta(Usuario usuario)
    }
}

' Singletons
package SingletonRepositories {
    ' Provavelmente vou salvar os dados em arquivos
    ' Classes que vão guardar conjuntos de dados

    ' Interface para salvamento
    interface IStorable {
        + String converterParaStringArmazenavel()
        + int pegarId()
    }

    IStorable <|... Usuario
    IStorable <|... Conta

    ' Algumas complicações com esse aqui.
    IStorable <|... ExtratoBancario

    interface Repository<T extends IStorable>{
        + void salvar(T entidade)
        + void deletar(T entidade)
    }

    class UserRepository {
        - static UserRepository instance

        + UserRepository()
        + static UserRepository getInstance()
    }

    class ContaRepository {
        - static ContaRepository instance

        + ContaRepository()
        + static ContaRepository getInstance()
    }

    ' Essa classe não foi criada
    class ExtratoRepository {
        ' Só há um extrato por conta, não sei se vou criar um repositório só pra ele.
        - static ExtratoRepository instance

        + ExtratoRepository()
        + static ExtratoRepository getInstance()
    }

    ' Relacionamentos
    Repository <|.down. UserRepository
    Repository <|.down. ContaRepository
    Repository <|.down. ExtratoRepository
    Repository --> IStorable
}

package SingletonSession{
    class SessionManager {
        - static SessionManager instance
        - Usuario usuarioLogado
        - Conta contaAtiva

        - SessionManager()
        + static SessionManager getInstance()
        + String getUsuarioLogado()
        + void setUsuarioLogado()
    }
}

@enduml